learning_log/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('learning_logs.urls')),
]

learning_logs/urls.py
"""Визначає юрл паттерни для длч кернінг логс"""

from django.urls import path
from . import views

app_name = 'learning_logs'
urlpatterns = [
    # головна сторінка
    path('', views.index, name='index'),
    # Сторінка, що відображає всі теми
    path('topics/', views.topics, name='topics'),
    # Сторінка, що присвячена окремій темі
    path('topics/<int:topic_id>', views.topic, name='topic'),
    # Сторінка для додавання нової теми
    path('new_topic/', views.new_topic, name='new_topic'),
    # новий допис
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    # Сторінка редагування допису
    path('edit_entry/<int:entry_id>', views.edit_entry, name='edit_entry'),
    # сторінка допису
    path('entry/<int:entry_id>', views.entry, name='entry'),
    # Видалення допису
    path('entry/<int:pk>/delete', views.EntryDeleteView.as_view(), name='entry_delete'),
]

users/urls.py
"""Визначити регулярні вирази URL"""

from django.urls import path, include

from . import views

app_name = 'users'
urlpatterns = [
    # додати уставні урл автентифікації
    path('', include('django.contrib.auth.urls')),
    # сторінка реєстрації
    path('register/', views.register, name='register'),
]

learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from taggit.managers import TaggableManager


class Topic(models.Model):
    """Тема, яку вивчає користувач"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        """Повернути рядкове представлення моделі"""
        return self.text


class Entry(models.Model):
    """Якась конкретна інформація до цієї теми"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = RichTextField(blank=True, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    entry_name = models.CharField(max_length=200)

    # https://django-taggit.readthedocs.io/en/latest/api.html#TaggableManager
    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Povernut ryadkove predstavlennya modeli"""
        if len(self.text) <= 50:
            return f"{self.text}"
        else:
            return f"{self.text[:50]}..."

learning_logs/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['entry_name', 'text', 'tags']
        labels = {'entry_name': 'Say my name!', 'text': '', 'tags': 'Add tags'}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

learning_logs/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.http import Http404
from django.core.paginator import Paginator  # відповідає за розбиття на сторінки
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy
from django.db.models import Q

from .models import Topic, Entry
from .forms import TopicForm, EntryForm


def index(request):
    """Головна сторінка журналу спостережень"""
    # реалізація пошуку
    strval = request.GET.get('search', False)  # GET - словник, get - метод
    if strval:
        query = Q(entry_name__icontains=strval)  # шукає по заголовку
        query.add(Q(text__icontains=strval), Q.OR)  # шукає по тексту
        query.add(Q(tags__name__in=[strval]), Q.OR)
        entries = Entry.objects.filter(query).select_related().order_by('-date_added').distinct()

        paginator = Paginator(entries, 10)  # показати 10 дописів на сторінці
        page_number = request.GET.get('page')  # гет реквест щоб отримати номер сторінки
        page_obj = paginator.get_page(page_number)  # отримати номер сторінки і відобразити її данні для контексту

        context = {'entries': entries, 'page': page_obj, 'search': strval}
        return render(request, 'learning_logs/search.html', context)

    return render(request, 'learning_logs/index.html')


# def check(request):
#     if Topic.owner != request.user:
#         raise Http404


@login_required()
def topics(request):
    """Показує усі теми"""
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'learning_logs/topics.html', context)


@login_required()
def topic(request, topic_id):
    """Показати одну тему та все що там введено"""
    topic = get_object_or_404(Topic, id=topic_id)
    # Пересвідчитись, що тема належить поточному користувачу
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')

    paginator = Paginator(entries, 10)  # показати 10 дописів на сторінці
    page_number = request.GET.get('page')  # гет реквест щоб отримати номер сторінки
    page_obj = paginator.get_page(page_number)  # отримати номер сторінки і відобразити її данні для контексту

    context = {'topic': topic, 'entries': entries, 'page': page_obj}
    return render(request, 'learning_logs/topic.html', context)


@login_required()
def entry(request, entry_id):
    """Показати один допис"""
    entry = get_object_or_404(Entry, id=entry_id)
    context = {'topic': topic, 'entry': entry}
    return render(request, 'learning_logs/entry.html', context)


@login_required()
def new_topic(request):
    """Додати нову тему"""
    if request.method != 'POST':
        # Жодних даних не відправлено; створити порожню форму
        form = TopicForm()
    else:
        # відправлений пост; обробити дані
        form = TopicForm(data=request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return redirect('learning_logs:topics')

    # Показати порожню або недійсну форму
    context = {'form': form}
    return render(request, 'learning_logs/new_topic.html', context)


@login_required()
def new_entry(request, topic_id):
    # Додати новий допис у наявну тему
    topic = Topic.objects.get(id=topic_id)
    # Пересвідчитись, що тема належить поточному користувачу
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        # Жодних даних не відправлено; стоврити порожню форму
        form = EntryForm()
    else:
        # Отримати дані у ПОСТ-запиті; обробити дані
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            form.save_m2m()
            return redirect('learning_logs:topic', topic_id=topic_id)
#
    # Показати порожню або недійсну форму.
    context = {'topic': topic, 'form': form}
    return render(request, 'learning_logs/new_entry.html', context)


@login_required()
def edit_entry(request, entry_id):
    """Редагувати існуючий допис"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    name = entry.entry_name
    if topic.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # сформувати запит; вивести поточний допис
        form = EntryForm(instance=entry)
    else:
        # Отримати дані у ПОСТ-запиті; обробити дані
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('learning_logs:topic', topic_id=topic.id)

    context = {'entry': entry, 'topic': topic, 'name': name, 'form': form}
    return render(request, 'learning_logs/edit_entry.html', context)


class EntryDeleteView(DeleteView):
    model = Entry
    template_name = 'learning_logs/entry_delete.html'

    def get_success_url(self):
        topic = self.object.topic
        return reverse('learning_logs:topic', args=[topic.pk])

learning_logs/templates/learning_logs/base.html
{% load bootstrap4 %}

<!docktype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width", initial-scale="1", shrink-to-fit="no">
    <title>Журнал спостережень</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    {% bootstrap_css %}
    {% bootstrap_javascript jquery='full' %}
    {{ form.media }}
</head>
<body>
    <nav class="navbar-expand-md navbar-dark bg-dark mb-4 border">

        <a class="navbar-brand" href="{% url 'learning_logs:index' %}">Журнал спостережень</a>

        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarCollapse" aria-controls="navbarCollapse"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggle-icon"></span></button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link" href="{% url 'learning_logs:topics'%}">Теми</a>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
                <span class="navbar-text"}>Привіт, {{ user.username }}</span>
            </li>
             <li class="nav-item">
                <a class="nav-link" href="{% url 'users:logout' %}">Вийти</a>
            </li>
          {% else %}
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:register' %}">Зареєструватися</a>
            </li>
            <li class="nav-item">
                <a class="nav-link" href="{% url 'users:login' %}">Увійти</a>
            </li>
            {% endif %}
        </ul>
    </div>

    </nav>

    <main role="main" class="container">
        <div class="pb-2 mb-2 border-bottom">
            {% block page_header %}{% endblock page_header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </main>

</body>

</html>

learning_logs/templates/learning_logs/edit_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Відредагуйте допис:</h2>
{% endblock page_header %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <form action="{% url 'learning_logs:edit_entry' entry.id %}" method='post' class="form">
      {% csrf_token %}
      {{ form.media }}
      {% bootstrap_form form %}
      <button name="submit" class="btn btn-dark">Відредагувати допис</button>
    </form>

{% endblock content%}

learning_logs/templates/learning_logs/entry.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1><a href="{% url 'learning_logs:topic' entry.topic.id %}">{{entry.topic}}</a></h1>
{% endblock page_header %}

{% block content %}

<p>{{ entry.date_added|date:'M d, Y H:i' }}</p>

        <div class="card mb-3">
            <h3 class="card-header">
                {{entry.entry_name}}
            </h3>
            <div class="card-body">
                {{ entry.text|safe }}
            </div>
            <div class="card-footer">
                {% for tag in entry.tags.all %}
                    <a href="{% url 'learning_logs:index' %}?search={{ tag }}">{{ tag }}</a>
                {% endfor %}
                <small><a href="{% url 'learning_logs:edit_entry' entry.id %}">Редагувати допис</a></small>
                <small><a href="{% url 'learning_logs:entry_delete' entry.id %}" style="float:right">Видалити допис</a></small>
            </div>
        </div>


{% endblock content%}

learning_logs/templates/learning_logs/entry_delete.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Видалення допису</h2>
{% endblock page_header %}

{% block content %}

    <p>Ви дійсно бажаєте видалити допис {{ entry.entry_name }}?</p>

    <form action="" method='post' class="form">
      {% csrf_token %}
      <button name="submit" class="btn btn-danger">Так, видалити</button>
    </form>

{% endblock content%}

learning_logs/templates/learning_logs/index.html
    {% extends "learning_logs/base.html" %}

    {% block page_header %}

<div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form>
        <input type="text" placeholder="Search.." name="search"
               {% if search %} value="{{ search }}" {% endif %}>
        <button type="submit"><i class="fa fa-search"></i></button>
        <a href="#"><i class="fa fa-undo"></i></a>
    </form>
</div>

    <ul>
    {% if user.is_authenticated %}

     <div class="jambotron">
        <h1 class="display-3">Ласкаво просимо!</h1>

        <p class="lead">Ви увійшли до вашого журналу спостережень.
            <br>
            Дізнались щось нове або хочете переглянути старі дописи? Просимо!
        </p>

        <a class="btn btn-lg btn-primary" href="{% url 'learning_logs:topics' %}" role="button">Перейти до ваших тем &raquo;</a>
    </div>

    {% else %}
        <div class="jambotron">
        <h1 class="display-3">Відстежуйте своє навчання.</h1>

        <p class="lead">Зробіть свій власний Журнал Спостережень та зберігайте список тем, які ви вивчаєте.
        Як тільки ви вивчили щось нове про тему, зробіть допис, щоб підсумувати що ви вивчили.</p>

        <a class="btn btn-lg btn-primary" href="{% url 'users:register' %}" role="button">Зареєструватися &raquo;</a>
    </div>
    {% endif %}



    {% endblock page_header%}

learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2>Додайте новий допис:</h2>
{% endblock page_header %}

{% block content %}

    <p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

    <form action="{% url 'learning_logs:new_entry' topic.id %}" method='post' class="form">

      {% csrf_token %}
      {{ form.media }}
      {% bootstrap_form form %}

      {% buttons %}
      <button name="submit" class="btn btn-dark btn-lg">Додати допис</button>
      {% endbuttons %}

    </form>

{% endblock content%}

learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap4 %}

{% block page_header %}
<h2> Додайте нову тему</h2>
{% endblock page_header %}

{% block content %}

    <form method='post' action="{% url 'learning_logs:new_topic' %}" class="form">
      {% csrf_token %}
      {% bootstrap_form form %}
      {% buttons %}
        <button name="submit" class="btn btn-primary btn-lg">Додати тему</button>
      {% endbuttons %}
    </form>

{% endblock content%}

learning_logs/templates/learning_logs/search.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>Пошук за запитом {{ search }}</h1>
{% endblock page_header %}

{% block content %}

<div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form>
        <input type="text" placeholder="Search.." name="search"
               {% if search %} value="{{ search }}" {% endif %}>
        <button type="submit"><i class="fa fa-search"></i></button>
        <a href="#"><i class="fa fa-undo"></i></a>
    </form>
</div>

    {% if search %}
      {% for entry in page %}
        <div class="card mb-3">
            <h4 class="card-header">
                <a href="{% url 'learning_logs:entry' entry.id %}">{{entry.entry_name}}</a>
                <br>
                <small class="text-muted" >{{ entry.date_added|date:'M d, Y H:i' }}</small>
            </h4>
            <div class="card-body">
                {{ entry.text|safe }}
            </div>
            <div class="card-footer text-muted">
                <!-- https://stackoverflow.com/questions/25345392/how-to-add-url-parameters-to-django-template-url-tag -->
                {% for tag in entry.tags.all %}
                    <a href="{% url 'learning_logs:index' %}?search={{ tag }}">{{ tag }}</a>
                {% endfor %}
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">Редагувати допис</a>
                <a href="{% url 'learning_logs:entry_delete' entry.id %}" style="float:right">Видалити допис</a>
            </div>
        </div>
      {% empty %}
        <p><h2>Нема результатів</h2></p>
      {% endfor %}
    {% endif %}

{% if page.has_other_pages %}
<div class="pagination"
     style="margin: 0 auto; width: 430px; background-color: GhostWhite;">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1">&laquo; Перша</a>
            <a href="?page={{ page.previous_page_number }}">Попередня</a>
        {% endif %}

        <span class="current">
            Сторінка {{ page.number }} з {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Наступна</a>
            <a href="?page={{ page.paginator.num_pages }}">Остання &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

{% endblock content %}

learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
    <h1>{{ topic|linebreaks }}</h1>
{% endblock page_header %}

{% block content %}

<div style="float:right">
    <!-- https://www.w3schools.com/howto/howto_css_search_button.asp -->
    <form>
        <input type="text" placeholder="Search.." name="search"
               {% if search %} value="{{ search }}" {% endif %}>
        <button type="submit"><i class="fa fa-search"></i></button>
        <a href="#"><i class="fa fa-undo"></i></a>
    </form>
</div>
    <p>
        <a href="{% url 'learning_logs:new_entry' topic.id %}">Додати новий допис</a>
    </p>

      {% for entry in page %}
        <div class="card mb-3">
            <h4 class="card-header">
                <a href="{% url 'learning_logs:entry' entry.id %}">{{entry.entry_name}}</a>
                <br>
                <small class="text-muted" >{{ entry.date_added|date:'M d, Y H:i' }}</small>
            </h4>
            <div class="card-body">
                {{ entry.text|safe }}
            </div>
            <div class="card-footer text-muted">
                {% for tag in entry.tags.all %}
                    <a href="{% url 'learning_logs:index' %}?search={{ tag }}">{{ tag }}</a>
                {% endfor %}
                <a href="{% url 'learning_logs:edit_entry' entry.id %}">Редагувати допис</a>
                <a href="{% url 'learning_logs:entry_delete' entry.id %}" style="float:right">Видалити допис</a>
            </div>
        </div>
      {% empty %}
        <p> Ще немає дописів до цієї теми </p>
      {% endfor %}

{% if page.has_other_pages %}
<div class="pagination"
     style="margin: 0 auto; width: 430px; background-color: GhostWhite;">
    <span class="step-links">
        {% if page.has_previous %}
            <a href="?page=1">&laquo; Перша</a>
            <a href="?page={{ page.previous_page_number }}">Попередня</a>
        {% endif %}

        <span class="current">
            Сторінка {{ page.number }} з {{ page.paginator.num_pages }}.
        </span>

        {% if page.has_next %}
            <a href="?page={{ page.next_page_number }}">Наступна</a>
            <a href="?page={{ page.paginator.num_pages }}">Остання &raquo;</a>
        {% endif %}
    </span>
</div>
{% endif %}

{% endblock content %}

learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block page_header %}
<h1>Теми</h1>
{% endblock page_header %}

{% block content %}

    <ul>
      {% for topic in topics %}
        <li><h3>
                {% if topic.text|length > 50 %}
            <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic|truncatechars:65 }}</a>
                {% else %}
            <a href="{% url 'learning_logs:topic' topic.id %}"> {{ topic }}</a>
                {% endif %}
        </h3></li>
      {% empty %}
        <li><h3> Ще не додано жодної теми. </h3></li>
      {% endfor %}
    </ul>

<h3><a href="{% url 'learning_logs:new_topic' %}">Додати нову тему</a></h3>

{% endblock content%}